# Generated by Django 3.0.7 on 2020-07-20 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dept_head_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
