# Generated by Django 3.0.7 on 2021-02-04 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_auto_20210204_0937'),
        ('easyaudit', '0014_auto_20200513_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0004_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyaudit.CRUDEvent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='requests.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_remarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
