# Generated by Django 3.0.7 on 2021-02-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='is_approve',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='remark',
            name='is_pass',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='remark',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='config.Status'),
            preserve_default=False,
        ),
    ]
