# Generated by Django 3.0.7 on 2021-03-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20210222_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='categorytype',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_archive',
        ),
    ]
