# Generated by Django 3.0.7 on 2021-08-13 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0014_auto_20200513_0008'),
        ('config', '0009_auto_20210416_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='easyaudit.CRUDEvent'),
        ),
    ]
