# Generated by Django 3.0.7 on 2021-10-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('config', '0011_auto_20210819_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='category_groups', to='auth.Group'),
        ),
    ]
