# Generated by Django 3.0.7 on 2022-07-04 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0012_category_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_explore_main', models.BooleanField(default=True)),
                ('is_explore_req_list', models.BooleanField(default=False)),
                ('is_explore_req_new', models.BooleanField(default=False)),
                ('is_explore_req_view', models.BooleanField(default=False)),
                ('is_explore_req_detail', models.BooleanField(default=False)),
                ('is_explore_profile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
