# Generated by Django 3.0.7 on 2022-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_explore_main',
            field=models.BooleanField(default=False),
        ),
    ]
