# Generated by Django 3.0.7 on 2022-08-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20220705_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_explore_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_explore_update',
            field=models.BooleanField(default=False),
        ),
    ]
