# Generated by Django 3.0.7 on 2022-05-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
