# Generated by Django 3.0.7 on 2022-06-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0029_auto_20220422_1326'),
        ('events', '0006_auto_20220512_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='requests.Ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='eventdate',
            unique_together={('event', 'date', 'time_start', 'time_end')},
        ),
    ]
