# Generated by Django 3.0.7 on 2022-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20220610_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='address',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='venue',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
