# Generated by Django 3.0.7 on 2022-07-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0014_auto_20220705_1354'),
        ('requests', '0030_requestformstatus_officer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ManyToManyField(blank=True, through='tasks.Member', to='tasks.Task')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='requests.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.Task'),
        ),
    ]
