# Generated by Django 3.0.7 on 2022-08-03 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0030_requestformstatus_officer'),
        ('config', '0014_auto_20220705_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='requests.Ticket')),
            ],
        ),
    ]
