# Generated by Django 3.0.7 on 2022-08-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220803_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_pending',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
