# Generated by Django 3.0.7 on 2022-08-11 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20220705_1354'),
        ('requests', '0031_auto_20220808_1350'),
        ('tasks', '0006_task_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_tasks', to='requests.Ticket')),
            ],
        ),
    ]
