# Generated by Django 3.0.7 on 2022-08-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0031_auto_20220808_1350'),
        ('tasks', '0006_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='opentask_str',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.RequestFormStatus'),
        ),
        migrations.CreateModel(
            name='OpenTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.RequestFormStatus')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_tasks', to='requests.Ticket')),
            ],
        ),
    ]
