# Generated by Django 3.0.7 on 2022-09-19 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220812_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.Task'),
        ),
    ]
