# Generated by Django 3.0.7 on 2021-01-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201216_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_user_password', 'Can change user password'),)},
        ),
    ]
