# Generated by Django 3.0.7 on 2021-03-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210121_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
