# Generated by Django 3.0.7 on 2021-03-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20210222_2126'),
        ('core', '0005_auto_20210303_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Department'),
        ),
    ]
