# Generated by Django 3.0.7 on 2021-10-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211001_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contant_no',
            new_name='contact_no',
        ),
    ]
