# Generated by Django 3.0.7 on 2021-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211001_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
    ]
