# Generated by Django 3.0.7 on 2021-12-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211215_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('change_user_password', 'Can change user password'), ('verify_user', 'Can verify user'))},
        ),
    ]
