# Generated by Django 3.0.7 on 2022-03-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20220221_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_publish',
        ),
    ]
