# Generated by Django 3.0.7 on 2020-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='formtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formtype',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
