# Generated by Django 3.0.7 on 2020-09-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20200819_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormType',
            new_name='RequestForm',
        ),
        migrations.RenameField(
            model_name='requestform',
            old_name='form_fields',
            new_name='fields',
        ),
    ]
