# Generated by Django 3.0.7 on 2020-09-09 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20200904_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='formtype_id',
            new_name='request_form',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
