# Generated by Django 3.0.7 on 2020-09-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200804_1044'),
        ('requests', '0004_auto_20200909_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='config.Category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
