# Generated by Django 3.0.7 on 2020-10-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_status'),
        ('requests', '0005_auto_20200916_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.ManyToManyField(related_name='forms', to='config.Status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Status'),
        ),
    ]
