# Generated by Django 3.0.7 on 2020-11-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_auto_20201019_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='status',
        ),
    ]
