# Generated by Django 3.0.7 on 2020-11-06 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_status'),
        ('requests', '0008_remove_requestform_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFormStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.RequestForm')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Status')),
            ],
        ),
        migrations.AddField(
            model_name='requestform',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='forms', through='requests.RequestFormStatus', to='config.Status'),
        ),
    ]
