# Generated by Django 3.0.7 on 2020-11-13 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0009_auto_20201106_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestform',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reference_no',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_tickets', to='config.Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='request_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formtype_tickets', to='requests.RequestForm'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_ticketes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_ticketes', to='config.Status'),
        ),
    ]
