# Generated by Django 3.0.7 on 2020-12-21 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0014_auto_20200513_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0010_auto_20201113_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyaudit.CRUDEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
