# Generated by Django 3.0.7 on 2021-01-27 06:22

from django.db import migrations, models
import django.utils.timezone
import requests.models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=requests.models.upload_file_url),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
