# Generated by Django 3.0.7 on 2021-02-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_auto_20210204_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestformstatus',
            old_name='has_apporving',
            new_name='has_approving',
        ),
        migrations.RenameField(
            model_name='requestformstatus',
            old_name='is_clent_step',
            new_name='is_client_step',
        ),
    ]
