# Generated by Django 3.0.7 on 2021-02-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('requests', '0017_auto_20210204_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='group',
        ),
        migrations.AddField(
            model_name='requestform',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.Group'),
        ),
    ]
