# Generated by Django 3.0.7 on 2021-02-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0018_auto_20210217_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='is_head_step',
            field=models.BooleanField(default=False),
        ),
    ]
