# Generated by Django 3.0.7 on 2021-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_auto_20210224_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
