# Generated by Django 3.0.7 on 2021-03-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_auto_20210304_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_archive',
        ),
    ]
