# Generated by Django 3.0.7 on 2021-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_auto_20210416_1433'),
        ('requests', '0024_auto_20210416_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_tickets', to='config.Category'),
        ),
    ]
