# Generated by Django 3.0.7 on 2021-08-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0027_auto_20210810_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
