# Generated by Django 3.0.7 on 2022-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0027_auto_20210810_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='has_event',
            field=models.BooleanField(default=False),
        ),
    ]
