# Generated by Django 3.0.7 on 2022-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0028_requestformstatus_has_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
