# Generated by Django 3.0.7 on 2022-07-11 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0029_auto_20220422_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestformstatus',
            name='officer',
            field=models.ManyToManyField(blank=True, related_name='status_officers', to=settings.AUTH_USER_MODEL),
        ),
    ]
