# Generated by Django 3.0.7 on 2022-09-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0031_auto_20220808_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestformstatus',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_forms', to='requests.RequestForm'),
        ),
    ]
